maintainer       "TheDgtl"
maintainer_email "Contact@TheDgtl.net"
license          "GPLv3"
description      "Installs/Configures multicraft"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "0.0.1"
depends          "java"
depends          "apache2"
depends          "php"
depends          "mysql"
depends          "database"
